// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNNpsywCl-lH4gKeLe2Avha_34Jp_1kM',
    appId: '1:602390345799:web:554395a1585c1c66f49962',
    messagingSenderId: '602390345799',
    projectId: 'store-9b59d',
    authDomain: 'store-9b59d.firebaseapp.com',
    storageBucket: 'store-9b59d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnVAnacq3y554CXXpJVItXJM9JDkUpKxY',
    appId: '1:602390345799:android:3eb8425b0a4ee384f49962',
    messagingSenderId: '602390345799',
    projectId: 'store-9b59d',
    storageBucket: 'store-9b59d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJI9gYDAFMWEUZEw1f5xexNmGNpP9PEGk',
    appId: '1:602390345799:ios:ec64599939e6d155f49962',
    messagingSenderId: '602390345799',
    projectId: 'store-9b59d',
    storageBucket: 'store-9b59d.appspot.com',
    iosBundleId: 'com.example.storeAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJI9gYDAFMWEUZEw1f5xexNmGNpP9PEGk',
    appId: '1:602390345799:ios:69458b302eb30d3ff49962',
    messagingSenderId: '602390345799',
    projectId: 'store-9b59d',
    storageBucket: 'store-9b59d.appspot.com',
    iosBundleId: 'com.example.storeAdminApp.RunnerTests',
  );
}
